volumes:
  pg_data:
  static_volume:

services:
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always

  backend:
    image: inferno681/pay2u_hackathon:latest
    env_file: .env
    volumes:
      - static_volume:/backend_static
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - ./media:/usr/share/nginx/html/media
    depends_on:
      - backend

  celery_worker:
    image: inferno681/pay2u_hackathon:latest
    env_file: .env
    volumes:
      - static_volume:/backend_static
    command: celery -A pay2u worker -l warning
    depends_on:
      - db
      - redis
      - backend

  celery_beat:
    image: inferno681/pay2u_hackathon:latest
    env_file: .env
    volumes:
      - static_volume:/backend_static
    command: celery -A pay2u beat -l warning
    depends_on:
      - db
      - redis
      - backend
