services:

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=mysecretpassword

volumes:
  db_value:
  static_volume:
