volumes:
  pg_data:
  static_volume:

services:
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: inferno681/pay2u_hackathon:latest
    env_file: .env
    volumes:
      - static_volume:/backend_static
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
    depends_on:
      - backend
