# Generated by Django 5.0.3 on 2024-03-24 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='annual_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена подписки за год'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cashback_procent',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% кэшбека'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена подписки за месяц'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='semi_annual_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена подписки за полгода'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cashback',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кэшбек'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость подписки'),
        ),
    ]
