# Generated by Django 5.0.3 on 2024-03-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='autorenewal',
            field=models.BooleanField(default=True, verbose_name='Автопродление'),
        ),
        migrations.AddField(
            model_name='cover',
            name='categories',
            field=models.ManyToManyField(to='subscriptions.category', verbose_name='Категории'),
        ),
    ]
