# Generated by Django 5.0.3 on 2024-03-28 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_usersubscription_autorenewal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ('end_date', 'price'), 'verbose_name': 'Пользователь/Подписка', 'verbose_name_plural': 'Пользователи/Подписки'},
        ),
    ]
