# Generated by Django 5.0.3 on 2024-03-31 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_usersubscription_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата начала подписки'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('done', 'Выполнена'), ('undone', 'Не выполнена')], default='undone', max_length=6, verbose_name='Статус транзакции')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='subscriptions.subscription', verbose_name='Подписка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ('timestamp',),
            },
        ),
        migrations.AlterField(
            model_name='subscription',
            name='users',
            field=models.ManyToManyField(through='subscriptions.Transaction', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
