# Generated by Django 5.0.3 on 2024-03-31 14:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('undone', 'Не выполнена'), ('done', 'Выполнена')], default='undone', max_length=6, verbose_name='Статус транзакции'),
        ),
    ]
