# Generated by Django 5.0.3 on 2024-04-01 23:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_transaction_amount_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Кэшбек'),
        ),
    ]
