# Generated by Django 5.0.3 on 2024-04-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_user_account_balance_alter_user_cashback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('done', 'Выполнена'), ('undone', 'Не выполнена')], default='undone', max_length=6, verbose_name='Статус транзакции'),
        ),
    ]
