# Generated by Django 5.0.3 on 2024-04-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.CharField(max_length=28, verbose_name='Описание'),
        ),
    ]
