# Generated by Django 5.0.3 on 2024-04-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_subscription_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='preview',
            field=models.CharField(max_length=24, verbose_name='Краткое описание'),
        ),
    ]
